nome = str(input('digite seu nome:')) .strip()
print('seu nome em letras maiuscilas e {}'.format(nome.upper()))
print('seu nome em letras minusculas e {}'.format(nome.lower()))
print('seu nome tem ao todo tem {} letras'.format(len(nome)-nome.count(' ')))
#print ('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome e {} e ele tem {} letras'.format(separa[0], len(separa[0])))
